### ISSUE TITLE
curry 부분도 있으면 좋겠습니답!

### ISSUE THREAD

**Issue by ppeeou** [marpple/window.functions.js#1]
너무 용량이 커지지만 않는다면 부분적용도요 ! ㅋㅋ

**Comment by ppeeou** [comment]
아 있군요.. !! 인자 2개까지..

**Comment by indongyoo** [comment]
용량은 좀 더 커져도 되는데, Partial.js를 같이 쓰려고 만든거라서^^;;
_clone이 있어야 할거 같아서 _extend, _defaults 정도는 왠지 들어갈 것 같아요.
